spring.application.name=flight-service

spring.datasource.url=jdbc:postgresql://localhost:5432/flyingcaio_flight
spring.datasource.username=flyingcaio
spring.datasource.password=flyingcaio

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true